# Generated by Django 3.2.4 on 2021-06-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('facebook_link', models.CharField(blank=True, max_length=255)),
                ('instagram_link', models.CharField(blank=True, max_length=255)),
                ('twitter_link', models.CharField(blank=True, max_length=255)),
                ('youtube_link', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
