# Generated by Django 3.2.4 on 2021-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='redirect_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
